### ISSUE TITLE
Featured Image on Pathways - does it do something?

### ISSUE THREAD

**Issue by brashrebel** [JacksonCollege/Academics-Management#10]
If there's a "grid image" option than what is the featured image for?

**Comment by banksashleym** [comment]
I would like each page of the site to have a top featured image to keep with the consistency of the site's look. I think it would be confusing for visitors to go to one page and have a featured image, and other pages with no featured image. For instance, we talked about doing feature banner image for each pathway that color coordinated with the pathways color scheme.

**Comment by joelworsham** [comment]
Right, the featured image is used as the banner
