### ISSUE TITLE
Add staff department "band" to bottom of program pages

### ISSUE THREAD

**Issue by joelworsham** [JacksonCollege/Academics-Management#16]

**Comment by banksashleym** [comment]
After thinking about this...instead of doing the band at the bottom, could the contact side nav link just link to a page with the listing of staff? 

Thanks!

**Comment by joelworsham** [comment]
Sure thing. So, completely do away with the gray band at the bottom, and instead of a link in the side-nav that lists the staff?

Should the staff list be a curated list of staff by the given department or list everyone?

Also, what should that link say?

**Comment by banksashleym** [comment]
Yes, i would like to do away with the gray band...in Human resources, we will have the entire list of employees in our employee directory, but for each section/department I would only like to pull out only  those employees that work in that departmetn. 

For instance, when creating the staff in the plugin, we have created the Marketing & Communications department and listed all 5 of us as being members of that department. So when a visitor goes to the Marketing/Communications "section" there will be a side nav link called "contact" and when they click that I would like it to pull and show only the marketing department staff.

**Comment by joelworsham** [comment]
This is no longer what we're going to do. We will be placing a link in the sidebar to a filtered staff list by department, as addressed here: JacksonCollege/Staff#28
