### ISSUE TITLE
Print stylesheet to match PDFs

### ISSUE THREAD

**Issue by joelworsham** [JacksonCollege/Academics-Management#19]
For Major Map and Printable Degree Map.

Basically just remove header/footer/sidebar.

Major Map should link to **printable** version of degree.

**Comment by joelworsham** [comment]
@banksashleym 

If you go to http://jacksoncollege.staging.wpengine.com/degree/testing-certificate/ (set to private, so must be logged in to view), I've setup the "Printable Degree Map" button to now work. Also, if you click on "TST 201" you'll notice there is a description dropdown.

My question is, do you want that description to be dropped down for all of the courses in the printable view?

**Comment by banksashleym** [comment]
This looks great! I don't think it will be necessary to populate the classes in the printable version - they can easily go back to the website and find the course descriptions.

Thanks!

**Comment by joelworsham** [comment]
:+1:
