### ISSUE TITLE
Academics Degree Page

### ISSUE THREAD

**Issue by joelworsham** [JacksonCollege/Academics-Management#2]
_From @banksashleym on December 7, 2015 17:38_

I'm assuming this is the case, but for each specific degree, will there be functionality when you click on/hover over a course title so that the description/credits comes up somewhere?

Thanks!

_Copied from original issue: JacksonCollege/Staff#14_

**Comment by joelworsham** [comment]
That is not yet implemented, though it definitely can be.

Do you have any mocks or ideas about how you would like the presentation of this?

**Comment by joelworsham** [comment]
@banksashleym Just wanted to check in on this one.

**Comment by banksashleym** [comment]
Sorry for not following up about this..Here is a mock up of what I was thinking. Just something simple - light gray background with darker gray border. and the course title, credits and pre-req's in the same color burgundy used throughout the site.

http://www.jccmi.edu/NewWebsite/CourseDescription.html

Thanks!

**Comment by joelworsham** [comment]
Thank you for mocking that up, but I actually realized that for this particular situation, it would work better if the content just appeared below each course row. This also allows support for no javascript because they will just all be visible if javascript is disabled in the client's browser.

**Comment by banksashleym** [comment]
Thanks, that works for me!
