### ISSUE TITLE
Program section - linking outside "pages" to programs

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Academics-Management#21]
I have been creating and uploading the additional program content as pages (for example, Radiography has there outcomes data, FAQ's, Program Application, etc...) so i create a parent page "Radiography" which doesn't have any information, since technically all of the Radiography program information is in the program page in the academics plugin...So then I create a child page under Radiography for each of the topics above and select "Radiography" in the program box you have created that will link this content with the program content from the plugin. 

All of the Radiography program pages info is showing up when I preview the program on the plugin side, however it is also pulling pages that I have created for other programs? For example, I have created a Vascular Sonography parent page and child pages, and selected Vascular Sonography as the program it should link to, but this information is showing up in Radiography?

**Comment by joelworsham** [comment]
I think this can now be accomplished with Site Sections, but let me know if you still have any issues.
