### ISSUE TITLE
Program section - linking outside "pages" to programs (consistent side nav)

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Academics-Management#22]
Is there a way when someone is in an academic program to keep the side navigation/featured image consistent when navigating to a page I have created with additional program content?

For instance, when I'm on the accounting program page and click on "2015-2016 accounting program guide" it takes me to the Accounting parent/child pages that I have created with additional program information. I can manually add in the featured image on these pages, but I would like it to appear seamless, with consistent side nav/feature image across all program information (those that were created in the plugin, and those pages that were created outside the plugin).

**Comment by joelworsham** [comment]
This can now be achieved with Site Sections (if you have any questions, let me know)

**Comment by banksashleym** [comment]
Thanks! I don't see an area or tab that says Site Sections anywhere? If you could point me in the direction that would be great.

**Comment by joelworsham** [comment]
Right. I'm actually doing an overhaul of the system. So hang tight for a little while and then I can fill  you in on the new system.

**Comment by joelworsham** [comment]
Alright, I've updated the system.

Sections can be found under Appearance -> Site Sections. You can add, delete, and edit them just like any other custom content type. You set the title and banner image like normal. There's also a metabox called "Section Content". This is a searchable field that allows you to add any number of any content type to the section. All content that belongs to the section will automatically pull in the title, banner, and *sidebar* for that page.

For the sidebar: Whenever you create a new section, a new sidebar is created and editable from Appearance -> Widgets. You can manage the section sidebars there and those sidebars will be used on the section pages.

Let me know how this system works out for you.

**Comment by banksashleym** [comment]
Sorry, I'm still not seeing the site sections in the appearance tab? Would i have to do anything on my end for that to show up?

Thanks!

**Comment by banksashleym** [comment]
Update: I am seeing the "enable site sections" that is available on each parent page. For instance, I went to the Cost and Financial Aid parent page, enabled it to be a site section and added a feature image. When I preview that cost & financial aid parent page, I see that the feature image is there, but it is not showing up on any of the child pages? I also created a custom sidebar nav menu, and enabled that - but it is only showing up on the parent cost & financial aid page and it takes on a different look than the side nav that was automatic that you had styled previously. When I click on any of the child pages it reverts back to the old sidebar and does not have a feature image

I see that I am able to add section content as far as the academic programs/events, etc..should I be able to add pages this way? Or should the child pages automatically inherit the feature image/sidebar that I set for the parent page section?

Let me know if I'm doing something wrong :) Thanks!

**Comment by joelworsham** [comment]
Sorry about the confusion. That part of the site has been in flux as we try to figure out the best approach to this. You are correct that site sections will now be managed by the parent page. Still working out the kinks of the presentation though, but in the end, any child page and any manually added "section content" will inherit the title, page banner, and sidebar.

**Comment by joelworsham** [comment]
Page children should now be working with site sections

**Comment by banksashleym** [comment]
Awesome, thanks so much! This is wonderful

**Comment by joelworsham** [comment]
:+1:

**Comment by banksashleym** [comment]
Sorry for jumping around on so many different topics today...I love these site sections and have been working on our department pages.

Now I am moving forward and re-configuring the academic program pages into site sections and have run into a stumbling block. Let me know if I am jumping the gun with this topic and if the site sections with program integration hasn't been fully developed yet.

I have started with the Accounting Program:

1. I start out on the accounting parent page - (which has multiple child pages) and have enabled it to be a site section. From there I enabled the sidebar and have created a custom navigation menu and have set the feature image. 

2. On the right hand side of the Accounting parent page in the dashboard I selected Accounting Program (the program page from the plugin) from the list of "Section Content," however nothing is showing up when I preview the page? It's only showing the Accounting parent/child pages.

I would like the Accounting Program (from the plugin) to show up as the "Accounting Home" page, which right now is the blank Accounting Parent Page. And then also be able to add a side link on the left "courses" which will pull all of the Accounting courses, and then also side nav links to the different accounting degrees - all in addition to the child pages that are currently listed.

**Comment by banksashleym** [comment]
Update: I was able to go through the path from the other end and preview the Accounting program page (from the plugin side) and the custom menu is now showing up on that end...however when clicking on one of the nav links from the custom menu it jumps now to the parent/child pages and doesn't incorporate any of the program information anymore? and it also changes the breadcrumbs to that of the parent/child relationships instead of the Home / Academics / Programs of Study / Program: Accounting?

I'm sorry this is creating such a mess!!

**Comment by banksashleym** [comment]
I just tested this out and I love how it's working. Perfect! If we could remove the bold (program) Home text and the list of degrees along the side navigation I think we should be good. I will create a custom menu for each program so that it looks like all the other pages.

Thank you so much for your work on this!!

**Comment by joelworsham** [comment]
Well, I actually am in progress of finishing this up :P I don't think it's currently working properly. I'm making a new checkbox when setting up a section called "Program Override". If you choose a program, then that section page will automatically use the program for the top level page.

**Comment by banksashleym** [comment]
Oops, I jumped the gun :) I will wait for this to be closed..THANK YOU!

**Comment by joelworsham** [comment]
Ha no worries! I'm hoping the new system will work well for you.

**Comment by joelworsham** [comment]
Alrighty all set. So go ahead now and set the program override where applicable, for instance, on the accounting section page, you will set the program override to the accounting program.
