### ISSUE TITLE
Import Courses from CSV

### ISSUE THREAD

**Issue by joelworsham** [JacksonCollege/Academics-Management#25]
Zip can be found [here](https://copy.com/WD4jgHodkd1w2O7d).

**Comment by banksashleym** [comment]
Sorry, I just logged in and saw there weren't any courses imported...should I do something with this zip file to get these uploaded? Is it as simple as doing an import of the zip file?

Thanks!!

**Comment by joelworsham** [comment]
This is something I'll be taking care of in the near future.

**Comment by banksashleym** [comment]
No worries, I just didn't know if it wasn't showing up for some reason :)

**Comment by joelworsham** [comment]
:+1:

**Comment by joelworsham** [comment]
@banksashleym All set
