### ISSUE TITLE
Academics breadcrumbs/navigation

### ISSUE THREAD

**Issue by joelworsham** [JacksonCollege/Academics-Management#3]
_From @joelworsham on December 8, 2015 15:14_

_From @banksashleym on December 7, 2015 17:46_

Could we structure the program pages so that each program (say Accounting) will have it's own left side navigation instead of using the academics side nav? A lot of programs have additional information that I would like to link to in addition to what's on the main landing page. Also, when a student gets as far as looking at the associate degree in accounting, the breadcrumbs and side nav don't offer a place to say go back to the accounting main page or even the business pathway, it just takes them back to the main pathways page where they have to select their pathway again.

Let me know if this is confusing and needs further explanation!

_Copied from original issue: JacksonCollege/Staff#15_

_Copied from original issue: JacksonCollege/Primary-Theme#19_

**Comment by joelworsham** [comment]
Sure, this makes sense.

As for the breadcrumbs, I know I did not follow the mocked crumbs, but there was a reason for this. Long story short, each "layer" of the academics system is created independently of the others. So you manage courses individually, and then eventually you can link to them from degrees. Same with programs to degrees and pathways to programs.

This system allows courses to belong to multiple degrees. It allows degrees to belong to multiple programs, and the same for pathways and programs.

What this does mean though is that the hierarchy is not static. Example:

You have course A and B (cA, cB), degree A and B (dA, dB), program A and B (pA, pB), and pathway A and B (pathA, pathB).

You can have any number of hierarchies established, like:

pathA -> pA -> dA -> cA
pathB -> pB -> dB -> cA
etc.

So you can see that course A belongs to multiple hierarchies. This means that when you're viewing cA, the crumbs could be *either* of those hierarchies. There's no way of telling. So displaying the hierarchies in the crumbs does not really work.

So because of this I've simplified the crumbs.

This same process will apply to the sidebar too. So I can give you per course (and degree and program and pathway) control of the sidebar, but there will be no distinguishing of which hierarchy the user is "in".

Does that make sense? It's very long-winded, I know.

**Comment by banksashleym** [comment]
Sounds great, and that makes a lot of sense...I kind of like the look and simplicity of the breadcrumbs, I think when you have too many it looks cluttered and gets really confusing!

As for the side navigation. Essentially I would like each program to be it's own section with it's own separate navigation. Say when you land on the main accounting landing page with all of the career/pay info I would like that to be the "Accounting home" page (even though it's technically not a "page" by wordpress terms...so on the left hand navigation, I would like the top link to say "accounting home" and then below that have the links to the degrees in accounting "associate degree" and "certificate" (which those would link to the degree page)...but then I would also like the functionality to be able to add additional links to pages with other accounting information. For instance the accounting program has an accounting handbook, so it would be nice to be able to add that to the side nav as well?

I would like to keep the structure similar to what we have now if that's doable? All of our programs now have similar side navs, but some have some extra links.
http://www.jccmi.edu/Academics/computerinformationsystems/accounting/

**Comment by joelworsham** [comment]
Sure thing, I will look into this.
